version: '2'
services:
  academy-api:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      COURSES_URL: '3.16.88.57'
      COURSES_PORT: '3000'
      COURSES_ENTRY: 'courses-ms/resources/courses'
    ports:
      - '5000:5000'
